genre/urls.py
from django.conf.urls import url

from . import views

app_name = 'genre'
urlpatterns = [
	url(r'^(?P<pageNumber>[1-9][0-9]*)/$', views.genres, name='genres'),
	url(r'^addGenre/$', views.addGenre, name='addgenres'),
	url(r'^editGenre/$', views.editGenre, name='editgenres'),
]

musique/urls.py
from django.conf.urls import url

from . import views

app_name = 'musique'
urlpatterns = [
	url(r'^$', views.index, name='index'),
	url(r'^search/$', views.searchTrack, name='search'),
	url(r'^addTrack/$', views.addTrackView, name='addTrackView'),
	url(r'^add/$', views.addTrack, name='add'),
	url(r'^edit/(?P<tid>[0-9]+)/$', views.editTrackView, name='edit'),
	url(r'^edited/$', views.editTrack, name='edited'),
]

say2gov_assignment/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
	url(r'^', include('musique.urls')),
	url(r'^genres/', include('genre.urls')),
	url(r'^admin/', admin.site.urls),
]

genre/models.py
from django.db import models

# Create your models here.

musique/models.py
from django.db import models

# Create your models here.

genre/views.py
from django.shortcuts import render
from django.views.decorators.csrf import ensure_csrf_cookie
import requests
import json

@ensure_csrf_cookie
def genres(request, pageNumber):
	r = requests.get('http://104.197.128.152:8000/v1/genres?page=' + pageNumber)
	
	hasNext = False
	hasPrev = False
	nextNum = -1
	prevNum = -1
	retVal = []

	jsonRespose = json.loads(r.text)

	if 'next' in jsonRespose and jsonRespose['next']:
		hasNext = True
		nextNum = int(pageNumber) + 1

	if 'previous' in jsonRespose and jsonRespose['previous']:
		hasPrev = True
		prevNum = int(pageNumber) - 1

	if 'results' in jsonRespose:
		retVal = jsonRespose['results']

	context = {
		'all_genres': retVal,
		'isNext': hasNext,
		'isPrev': hasPrev,
		'nextNum': nextNum,
		'prevNum': prevNum
	}
	
	return render(request, 'genre/genres.html', context)

def addGenre(request):
	#error handling
	parameters = {
		'name': request.POST.get('name')
	}

	r = requests.post('http://104.197.128.152:8000/v1/genres', data = parameters)

	context = {
		'mess': 'Genre added.'
	}

	return render(request, 'genre/editgenres.html', context)

def editGenre(request):
	mess = "Genre edited."

	if request.POST.get('name') == "":
		mess = "Genre not edited. Empty string."
	else:
		parameters = {
			'id': int(request.POST.get('id')),
			'name': request.POST.get('name')
		}

		r = requests.post('http://104.197.128.152:8000/v1/genres/' + request.POST.get('id'), data = parameters)

	context = {
		'mess': mess,
	}

	return render(request, 'genre/editgenres.html', context)

musique/views.py
from django.http import Http404
from django.shortcuts import render
import requests
import json

def index(request):
	try:
		pageNumber = int(request.GET.get('page', 1))
		#check if integer, try with other value: out of range, char
	except Exception:
		raise Http404("Does not exist")

	r = requests.get('http://104.197.128.152:8000/v1/tracks?page=' + str(pageNumber))
	
	hasNext = False
	hasPrev = False
	nextNum = -1
	prevNum = -1
	retVal = []

	jsonRespose = json.loads(r.text)

	if 'next' in jsonRespose and jsonRespose['next']:
		hasNext = True
		nextNum = pageNumber + 1

	if 'previous' in jsonRespose and jsonRespose['previous']:
		hasPrev = True
		prevNum = pageNumber - 1

	if 'results' in jsonRespose:
		retVal = jsonRespose['results']

		for item in retVal:
			item['ratingOld'] = item['rating'] #for edit track
			item['rating'] = int(round(float(item['rating']), 0))

	context = {
		'all_tracks': retVal,
		'isNext': hasNext,
		'isPrev': hasPrev,
		'nextNum': nextNum,
		'prevNum': prevNum
	}
	
	return render(request, 'musique/index.html', context)

def searchTrack(request):
	q = request.GET.get('q')

	parameters = {'title': q}

	r = requests.get('http://104.197.128.152:8000/v1/tracks', params = parameters)
	jsonRespose = json.loads(r.text)
	matchedSongs = []

	#try with different track names (existent and non-existent)

	if 'results' in jsonRespose:
		while jsonRespose['next'] is not None:
			if 'results' in jsonRespose:
				for item in jsonRespose['results']:
					item['ratingOld'] = item['rating'] #for edit track
					item['rating'] = int(round(float(item['rating']), 0))
					matchedSongs.append(item)

			r = requests.get(jsonRespose['next'])
			jsonRespose = json.loads(r.text)

		if 'results' in jsonRespose:
			for item in jsonRespose['results']:
				item['ratingOld'] = item['rating'] #for edit track
				item['rating'] = int(round(float(item['rating']), 0))
				matchedSongs.append(item)

	context = {'matchedTracks': matchedSongs}

	return render(request, 'musique/search.html', context)

def addTrackView(request):
	tid = request.POST.get('id')

	r = requests.get('http://104.197.128.152:8000/v1/genres')

	jsonRespose = json.loads(r.text)
	allGenres = []

	if 'results' in jsonRespose:
		while jsonRespose['next'] is not None:
			if 'results' in jsonRespose:
				for item in jsonRespose['results']:
					allGenres.append(item)

			r = requests.get(jsonRespose['next'])
			jsonRespose = json.loads(r.text)

		if 'results' in jsonRespose:
			for item in jsonRespose['results']:
				allGenres.append(item)

	context = {'allGenres': allGenres}

	return render(request, 'musique/addTrackView.html', context)

def addTrack(request):
	nameVal = request.POST.get('name')
	ratingVal = request.POST.get('rating')
	genreVal = request.POST.getlist('genrelist')

	parameters = {
		'title': nameVal,
		'rating': ratingVal,
		'genres': genreVal
	}

	r = requests.post('http://104.197.128.152:8000/v1/tracks', data = parameters)

	context = {
		'mess': 'Track added.'
	}

	return render(request, 'musique/added.html', context)

def editTrackView(request, tid):
	r = requests.get('http://104.197.128.152:8000/v1/genres')

	jsonRespose = json.loads(r.text)
	allGenres = []

	if 'results' in jsonRespose:
		while jsonRespose['next'] is not None:
			if 'results' in jsonRespose:
				for item in jsonRespose['results']:
					allGenres.append(item)

			r = requests.get(jsonRespose['next'])
			jsonRespose = json.loads(r.text)

		if 'results' in jsonRespose:
			for item in jsonRespose['results']:
				allGenres.append(item)

	r = requests.get('http://104.197.128.152:8000/v1/tracks/' + tid)

	jsonRespose = json.loads(r.text)

	context = {}
		
	context = {
		'trackInfo': jsonRespose,
		'allGenres': allGenres
	}

	return render(request, 'musique/editTrackView.html', context)

def editTrack(request):
	idVal = request.POST.get('id')
	nameVal = request.POST.get('name')
	ratingVal = request.POST.get('rating')
	genreVal = request.POST.getlist('genrelist')

	parameters = {
		'id': idVal,
		'title': nameVal,
		'rating': ratingVal,
		'genres': genreVal
	}

	r = requests.post('http://104.197.128.152:8000/v1/tracks/' + idVal, data = parameters)

	context = {
		'mess': 'Track edited.'
	}

	return render(request, 'musique/added.html', context)

genre/templates/genre/editgenres.html
<head>
	<title>Musique</title>
	<META http-equiv="refresh" content="3; URL={% url 'genre:genres' 1 %}"> 
</head>
<p>{{ mess }} Redirecting in 3 seconds.</p>

genre/templates/genre/genres.html
{% load static %}

<head>
	<link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
	<link rel="stylesheet" href="https://code.getmdl.io/1.3.0/material.indigo-pink.min.css">
	<link rel="stylesheet" type="text/css" href="{% static 'genre/gindex.css' %}" />
	<script defer src="https://code.getmdl.io/1.3.0/material.min.js"></script>
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/js-cookie/2.1.4/js.cookie.js"></script>
	<title>Musique</title>
	
	<script type="text/javascript">
		function validateForm() {
			var x = document.getElementById("addGen").value.toString().trim();
			
			if (x == "") {
				alert("Empty string");
				return false;
			}

			return true;
		}

		function post(path, params, method) {
			method = method || "post";
			var form = document.createElement("form");
			form.setAttribute("method", method);
			form.setAttribute("action", path);

			for(var key in params) {
				if(params.hasOwnProperty(key)) {
					var hiddenField = document.createElement("input");
					hiddenField.setAttribute("type", "hidden");
					hiddenField.setAttribute("name", key);
					hiddenField.setAttribute("value", params[key]);

					form.appendChild(hiddenField);
				}
			}

			var hiddenField1 = document.createElement("input");
			hiddenField1.setAttribute("type", "hidden");
			hiddenField1.setAttribute("name", 'csrfmiddlewaretoken');
			hiddenField1.setAttribute("value", Cookies.get('csrftoken'));
			form.appendChild(hiddenField1);

			document.body.appendChild(form);
			form.submit();
		}

		function validate2(inp, inpid) {
			post("{% url 'genre:editgenres' %}", {'name': inp.toString().trim(), 'id': inpid});
		}

		$(document).on('click', '[data-editable]', function() {
			var $el = $(this);
			var $id = $el.attr('id');
			var $input = $('<input/>').val($el.text());
			$el.replaceWith($input);

			var save = function(){
				validate2($input.val(), $id);
			};

			$input.one('blur', save).focus();
		});
	</script>
	<style type="text/css">
		.demo-list-item {
			width: 100%;
		}
		body {
			font-family: 'Roboto', 'Helvetica', sans-serif;
			margin: 0;
			padding: 0;
		}

		.mdl-demo .mdl-layout__header-row {
			padding-left: 40px;
		}
		.mdl-demo .mdl-layout.is-small-screen .mdl-layout__header-row h3 {
			font-size: inherit;
		}
		.mdl-demo main > .mdl-layout__tab-panel {
			padding: 8px;
			padding-top: 48px;
		}
		.mdl-demo .mdl-card {
			height: auto;
			display: flex;
			flex-direction: column;
		}
		.mdl-demo .mdl-card > * {
			height: auto;
		}
		.mdl-demo .mdl-layout__content section:not(:last-of-type) {
			position: relative;
			margin-bottom: 48px;
		}
		.mdl-demo section.section--center {
			max-width: 860px;
		}
		.mdl-demo section > header{
			display: flex;
			align-items: center;
			justify-content: center;
		}
		.mdl-demo section > header > .material-icons {
			font-size: 3rem;
		}
		.mdl-demo section > button {
			position: absolute;
			z-index: 99;
			top: 8px;
			right: 8px;
		}
	</style>
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>

<body class="mdl-demo mdl-color--grey-100 mdl-color-text--grey-700 mdl-base">
	<div class="mdl-layout mdl-js-layout mdl-layout--fixed-header">
		<header class="mdl-layout__header mdl-layout__header--scroll mdl-color--primary">
			<div class="mdl-layout--large-screen-only mdl-layout__header-row">
			</div>
			<div class="mdl-layout--large-screen-only mdl-layout__header-row">
				<h3>Genres</h3>
			</div>
			<div class="mdl-layout--large-screen-only mdl-layout__header-row">
			</div>
		</header>
		<main class="mdl-layout__content">
			<br>
			<br>
			<br>
			<section class="section--center mdl-grid mdl-grid--no-spacing mdl-shadow--2dp">
				<div style="text-align: center" class="mdl-card mdl-cell mdl-cell--12-col">
					<br>
					<br>
					<form action="{% url 'genre:addgenres' %}" method="post" onsubmit="return validateForm()">
						{% csrf_token %}
						<div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
							<input class="mdl-textfield__input" type="text" name="name" id="addGen">
							<label class="mdl-textfield__label" for="addGen">Add genre</label>
						</div>
					</form>
				</div>
			</section>
			<section class="section--center mdl-grid mdl-grid--no-spacing mdl-shadow--2dp">
				<div class="mdl-card mdl-cell mdl-cell--12-col">
					{% block genresData %}
						{% for genre in all_genres %}
							<ul class="demo-list-item mdl-list">
								<li class="mdl-list__item">
									<span class="mdl-list__item-primary-content" id="{{ genre.id }}" data-editable>{{ genre.name }}</span>
								</li>
							</ul>
						{% endfor %}
						<table style="width:100%">
							<tr>
								<td align="center">
									{% if isPrev %}
										<a href="{% url 'genre:genres' prevNum %}">
										<button class="mdl-button mdl-js-button mdl-button--fab mdl-js-ripple-effect mdl-button--colored">
											<i class="material-icons">&#xE5C4</i>
										</button>
										</a>
									{% else %}
										<button class="mdl-button mdl-js-button mdl-button--fab mdl-js-ripple-effect mdl-button--colored" disabled>
											<i class="material-icons">&#xE5C4</i>
										</button>
									{% endif %}
								</td>
								<td align="center">
									{% if isNext %}
										<a href="{% url 'genre:genres' nextNum %}">
										<button class="mdl-button mdl-js-button mdl-button--fab mdl-js-ripple-effect mdl-button--colored">
											<i class="material-icons">&#xE5C8</i>
										</button>
										</a>
									{% else %}
										<button class="mdl-button mdl-js-button mdl-button--fab mdl-js-ripple-effect mdl-button--colored" disabled>
											<i class="material-icons">&#xE5C8</i>
										</button>
									{% endif %}
								</td>
							</tr>
						</table>
						<br>
						<br>
					{% endblock %}
				</div>
			</section>
			<br>
			<br>
		</main>
	</div>
</body>

musique/templates/musique/addTrackView.html
{% load static %}

<head>
	<title>Musique</title>

	<link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
	<link rel="stylesheet" href="https://code.getmdl.io/1.3.0/material.indigo-pink.min.css">
	<link rel="stylesheet" type="text/css" href="{% static 'musique/mod.css' %}" />
	<script defer src="https://code.getmdl.io/1.3.0/material.min.js"></script>

	<meta name="viewport" content="width=device-width, initial-scale=1.0">

	<script type="text/javascript">
		function validateForm() {
			var x = document.getElementById("traNam").value.toString().trim();
			
			if (x == "") {
				alert("Empty name");
				return false;
			}

			return true;
		}
	</script>

	<style type="text/css">
		.CBcontainer {
			width: auto;
			height: 40%;
			overflow-y: scroll;
			display: block;
		}
		body {
			font-family: 'Roboto', 'Helvetica', sans-serif;
			margin: 0;
			padding: 0;
		}

		.mdl-demo .mdl-layout__header-row {
			padding-left: 40px;
		}
		.mdl-demo .mdl-layout.is-small-screen .mdl-layout__header-row h3 {
			font-size: inherit;
		}
		.mdl-demo main > .mdl-layout__tab-panel {
			padding: 8px;
			padding-top: 48px;
		}
		.mdl-demo .mdl-card {
			height: auto;
			display: flex;
			flex-direction: column;
		}
		.mdl-demo .mdl-card > * {
			height: auto;
		}
		.mdl-demo .mdl-layout__content section:not(:last-of-type) {
			position: relative;
			margin-bottom: 48px;
		}
		.mdl-demo section.section--center {
			max-width: 860px;
		}
		.mdl-demo section > header{
			display: flex;
			align-items: center;
			justify-content: center;
		}
		.mdl-demo section > button {
			position: absolute;
			display: block;
			z-index: 99;
			top: 8px;
			right: 8px;
		}
	</style>
</head>

<body class="mdl-demo mdl-color--grey-100 mdl-color-text--grey-700 mdl-base">
	<div class="mdl-layout mdl-js-layout mdl-layout--fixed-header">
		<header class="mdl-layout__header mdl-layout__header--scroll mdl-color--primary">
			<div class="mdl-layout--large-screen-only mdl-layout__header-row">
			</div>
			<div class="mdl-layout--large-screen-only mdl-layout__header-row">
				<h3>Add Track</h3>
			</div>
			<div class="mdl-layout--large-screen-only mdl-layout__header-row">
			</div>
		</header>
		<main class="mdl-layout__content">
			<br>
			<br>
			<br>
			<section class="section--center mdl-grid mdl-grid--no-spacing mdl-shadow--2dp">
				<div style="text-align: center;" class="mdl-card mdl-cell mdl-cell--12-col">
					<form action="{% url 'musique:add' %}" onsubmit="return validateForm()" method="post">
						{% csrf_token %}
						<br>
						<br>
						<div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
							<input class="mdl-textfield__input" type="text" name="name" id="traNam">
							<label class="mdl-textfield__label" for="traNam">Track Name</label>
						</div>
						<br>
						<br>
						<div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
							<input class="mdl-textfield__input" type="text" pattern="[0-9]\.[0-9]" name="rating" id="rat" required="true">
							<label class="mdl-textfield__label" for="rat">Rating</label>
						</div>
						<br>
						<br>
						<div class="CBcontainer">
							{% for genre in allGenres %}
							<label class="mdl-checkbox mdl-js-checkbox mdl-js-ripple-effect" for="{{ genre.id }}">
								<input type="checkbox" id="{{ genre.id }}" value="{{ genre.id }}" class="mdl-checkbox__input" name="genrelist">
								<span class="mdl-checkbox__label">{{ genre.name }}</span>
							</label>
							{% endfor %}
						</div>
						<br>
						<br>
						<button class="mdl-button mdl-js-button mdl-button--raised mdl-button--colored" type="submit">Submit</button>
					</form>
				</div>
			</section>
		</main>
	</div>
</body>

musique/templates/musique/added.html
<head>
	<title>Musique</title>
	<META http-equiv="refresh" content="3; URL={% url 'musique:index' %}"> 
</head>
<p>{{ mess }} Redirecting in 3 seconds.</p>

musique/templates/musique/index.html
{% load static %}

<head>
	<link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
	<link rel="stylesheet" href="https://code.getmdl.io/1.3.0/material.indigo-pink.min.css">
	<link rel="stylesheet" type="text/css" href="{% static 'musique/index.css' %}" />
	<script defer src="https://code.getmdl.io/1.3.0/material.min.js"></script>
	<title>Musique</title>

	<script type="text/javascript">
		function validateForm() {
			var x = document.forms["addTrackForm"]["name"].value.toString().trim();
			
			if (x == "") {
				alert("Invalid name");
				return false;
			}

			x = document.forms["addTrackForm"]["rating"].value.toString().trim();
			x = Number(x);

			if(Number.isNaN(x)) {
				alert("Invalid rating");
				return false;
			} else if(Math.round((x * 10) / 10) <= 0.0 || Math.round((x * 10) / 10) > 10.0) {
				alert("Range for rating (0.0, 10.0]");
				return false;
			}

			document.forms["addTrackForm"]["rating"].value = Math.round((x * 10) / 10);

			x = document.forms["addTrackForm"]["genre"].value.toString().trim();

			return true;
		}
	</script>
	<style>
		.demo-list-two {
			width: 100%;
		}

		body {
			font-family: 'Roboto', 'Helvetica', sans-serif;
			margin: 0;
			padding: 0;
		}

		.mdl-demo .mdl-layout__header-row {
			padding-left: 40px;
		}
		.mdl-demo .mdl-layout.is-small-screen .mdl-layout__header-row h3 {
			font-size: inherit;
		}
		.mdl-demo main > .mdl-layout__tab-panel {
			padding: 8px;
			padding-top: 48px;
		}
		.mdl-demo .mdl-card {
			height: auto;
			display: flex;
			flex-direction: column;
		}
		.mdl-demo .mdl-card > * {
			height: auto;
		}
		.mdl-demo .mdl-layout__content section:not(:last-of-type) {
			position: relative;
			margin-bottom: 48px;
		}
		.mdl-demo section.section--center {
			max-width: 860px;
		}
		.mdl-demo section > header{
			display: flex;
			align-items: center;
			justify-content: center;
		}
		.mdl-demo section > header > .material-icons {
			font-size: 3rem;
		}
		.mdl-demo section > button {
			position: absolute;
			z-index: 99;
			top: 8px;
			right: 8px;
		}
	</style>
	<!--
	https://stackoverflow.com/questions/24622132/call-a-dynamic-python-function-after-the-webpage-is-loaded-in-django
	make genre list load via this
	-->
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>

<body class="mdl-demo mdl-color--grey-100 mdl-color-text--grey-700 mdl-base">
	<div class="mdl-layout mdl-js-layout mdl-layout--fixed-header">
		<header class="mdl-layout__header mdl-layout__header--scroll mdl-color--primary">
			<div class="mdl-layout--large-screen-only mdl-layout__header-row">
			</div>
			<div class="mdl-layout--large-screen-only mdl-layout__header-row">
				<h3>Tracks</h3>
			</div>
			<div class="mdl-layout--large-screen-only mdl-layout__header-row">
			</div>
		</header>
		<main class="mdl-layout__content">
			<br>
			<br>
			<br>
			<section class="section--center mdl-grid mdl-grid--no-spacing mdl-shadow--2dp">
				<div style="text-align: center;" class="mdl-card mdl-cell mdl-cell--12-col">
					<br>
					<br>
					<a style="margin-right: 10%" href="{% url 'genre:genres' 1 %}">
						<button class="mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect mdl-button--accent" style="position:absolute; left=50%">Genres</button>
					</a>
					<br>
					<br>
					<br>
					<a style="margin-right: 12%" href="{% url 'musique:addTrackView' %}">
						<button class="mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect mdl-button--accent" style="position:absolute; right=50%">Add Track</button>
					</a>
					<br>
					<br>
					<br>
					<form action="{% url 'musique:search' %}">
						<div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
							<input class="mdl-textfield__input" type="text" name="q" id="seaTra">
							<label class="mdl-textfield__label" for="seaTra">Search track</label>
						</div>
					</form>
					<br>
				</div>
			</section>

			<section class="section--center mdl-grid mdl-grid--no-spacing mdl-shadow--2dp">
				<div class="mdl-card mdl-cell mdl-cell--12-col">
					{% block tracksData %}
						<ul class="demo-list-two mdl-list">
							{% for track in all_tracks %}
								<li class="mdl-list__item mdl-list__item--two-line">
									<span class="mdl-list__item-primary-content">
										<i class="material-icons mdl-list__item-avatar">&#xE405</i>
										<a href="{% url 'musique:edit' track.id %}">{{ track.title }}</a>
										<span class="mdl-list__item-sub-title">
											[
											{% for genre in track.genres %}
												{% if forloop.last %}
													{{ genre.name }}
												{% else %}
													{{ genre.name }}, 
												{% endif %}
											{% endfor %}
											]
										</span>
									</span>
								
									<span class="mdl-list__item-secondary-content">
										{% if forloop.first %}
											<span class="mdl-list__item-secondary-info">Rating</span>
										{% endif %}

										<table>
											<tr>
												{% if track.rating == 0 %}
													<td><a class="mdl-list__item-secondary-action"><i class="material-icons">&#xE83A</i></a></td>
												{% elif track.rating > 0 and track.rating <= 1 %}
													<td><a class="mdl-list__item-secondary-action"><i class="material-icons">&#xE839</i></a></td>
												{% elif track.rating > 1 %}
													<td><a class="mdl-list__item-secondary-action"><i class="material-icons">&#xE838</i></a></td>
												{% endif %}

												{% if track.rating <= 2 %}
													<td><a class="mdl-list__item-secondary-action"><i class="material-icons">&#xE83A</i></a></td>
												{% elif track.rating > 2 and track.rating <= 3 %}
													<td><a class="mdl-list__item-secondary-action"><i class="material-icons">&#xE839</i></a></td>
												{% elif track.rating > 3 %}
													<td><a class="mdl-list__item-secondary-action"><i class="material-icons">&#xE838</i></a></td>
												{% endif %}

												{% if track.rating <= 4 %}
													<td><a class="mdl-list__item-secondary-action"><i class="material-icons">&#xE83A</i></a></td>
												{% elif track.rating > 4 and track.rating <= 5 %}
													<td><a class="mdl-list__item-secondary-action"><i class="material-icons">&#xE839</i></a></td>
												{% elif track.rating > 5 %}
													<td><a class="mdl-list__item-secondary-action"><i class="material-icons">&#xE838</i></a></td>
												{% endif %}

												{% if track.rating <= 6 %}
													<td><a class="mdl-list__item-secondary-action"><i class="material-icons">&#xE83A</i></a></td>
												{% elif track.rating > 6 and track.rating <= 7 %}
													<td><a class="mdl-list__item-secondary-action"><i class="material-icons">&#xE839</i></a></td>
												{% elif track.rating > 7 %}
													<td><a class="mdl-list__item-secondary-action"><i class="material-icons">&#xE838</i></a></td>
												{% endif %}

												{% if track.rating <= 8 %}
													<td><a class="mdl-list__item-secondary-action"><i class="material-icons">&#xE83A</i></a></td>
												{% elif track.rating > 8 and track.rating <= 9 %}
													<td><a class="mdl-list__item-secondary-action"><i class="material-icons">&#xE839</i></a></td>
												{% elif track.rating > 9 %}
													<td><a class="mdl-list__item-secondary-action"><i class="material-icons">&#xE838</i></a></td>
												{% endif %}
											</tr>
										</table>
									</span>
								</li>
							{% endfor %}
						</ul>
						<table style="width:100%">
							<tr>
								<td align="center">
									{% if isPrev %}
										<a href="?page={{ prevNum }}">
										<button class="mdl-button mdl-js-button mdl-button--fab mdl-js-ripple-effect mdl-button--colored">
											<i class="material-icons">&#xE5C4</i>
										</button>
										</a>
									{% else %}
										<button class="mdl-button mdl-js-button mdl-button--fab mdl-js-ripple-effect mdl-button--colored" disabled>
											<i class="material-icons">&#xE5C4</i>
										</button>
									{% endif %}
								</td>
								<td align="center">
									{% if isNext %}
										<a href="?page={{ nextNum }}">
										<button class="mdl-button mdl-js-button mdl-button--fab mdl-js-ripple-effect mdl-button--colored">
											<i class="material-icons">&#xE5C8</i>
										</button>
										</a>
									{% else %}
										<button class="mdl-button mdl-js-button mdl-button--fab mdl-js-ripple-effect mdl-button--colored" disabled>
											<i class="material-icons">&#xE5C8</i>
										</button>
									{% endif %}
								</td>
							</tr>
						</table>
						<br>
						<br>
					{% endblock %}
				</div>
			</section>
			<br>
			<br>
		</main>
	</div>
</body>